# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'OneDriveSDK' do
    pod 'ADAL', '~> 1.2'
    pod 'Base32', '~> 1.1'
end

target 'OneDriveSDKTests' do
    pod 'OCMock'
end

def append_header_search_path(target, path)
    target.build_configurations.each do |config|
        # Note that there's a space character after `$(inherited)`.
        config.build_settings["HEADER_SEARCH_PATHS"] ||= "$(inherited) "
        config.build_settings["HEADER_SEARCH_PATHS"] << path
    end
end

pre_install do |installer|
    installer.pods_project.targets.each do |target|
        append_header_search_path(target, "${FARHADLIBRARY_FRW}")
        if target_name == "OneDriveSDK"
            target.build_configurations.each do |config|
                # Note that there's a space character after `$(inherited)`.
                config.build_settings["MACH_O_TYPE"] = "staticlib"
            end
        end
    end
end
